baseURL = 'https://wewillnevermeet.github.io'
languageCode = 'en-us'
title = '世间的一切都值得纪念'
defaultContentLanguage = 'zh'
theme = 'PaperMod'
[params]
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false